### ISSUE TITLE
Android Dev

### ISSUE THREAD

**Issue by felipefpx** [fractaltecnologia/jobs#1]
<p align="center"><img src="http://fractaltecnologia.com.br/wp-content/uploads/2017/08/logo.png" height="250px"/></p>

## Descrição da vaga

Procuramos um desenvolvedor Android, organizado, antenado em novas tecnologias, disposto a aprender e compartilhar conhecimentos. A Fractal é uma das maiores empresas brasileiras de tecnologia voltadas a educação, com importantes clientes e parceiros (como a Saraiva e a Kroton). Estamos buscando ampliar nossa equipe e queremos alguém que esteja disposto a crescer em conjunto com a nossa empresa. Buscamos um profissional proativo e super interessado em aprender novas tecnologias, mas que já tenha conhecimentos específicos necessários para acompanhar os projetos da nossa empresa. 

Temos um ambiente de trabalho flexível e descontraído, com uma equipe bastante receptiva e colaborativa, onde sua opinião é importante para crescermos juntos.

## Local

• Presencial, em João Pessoa, PB
• Remoto

## Benefícios

• Bonificação na forma do pagamento de 70% do valor do plano de saúde AMIL 
• Horário flexível 
• Possibilidade de home office também para desenvolvedores presenciais
• Escritório com área de lazer 
• Ambiente de trabalho descontraído

## Requisitos

Obrigatórios
• 1 ano ou mais de experiência com desenvolvimento Android 
• Android Studio e Gradle
• Kotlin
• Uncle Bob's Clean Architecture
• Padrão MVP
• Consumo de APIs RESTful 
• Material Design Guidelines
• Criação de layouts XML
• Princípios SOLID
• Git
• SCRUM
• Inglês
• Proativo 
• Interessado em aprender

Diferenciais
• RxJava 2 
• Dagger 2 
• ConstraintLayout 
• Padrão MVVM 
• Testes unitários e instrumentados
     - JUnit
     - Mockito
     - Espresso 
• Realm DB 
• Programação funcional 
• Animações e transições

## Contratação

Pessoa Jurídica, com salário a combinar.

## Como se candidatar

Por favor envie um email para recrutamento@fractaltecnologia.com.br com seu CV em anexo e com o assunto:
- Para concorrer a posição de Android Dev Júnior:  **[GitHub] Vaga Android Dev JR**
- Para concorrer a posição de Android Dev Pleno:  **[GitHub] Vaga Android Dev Pleno**

## Nosso novo escritório recém inaugurado em João Pessoa - PB

<p align="center"><img src="https://lh3.googleusercontent.com/d10RJZ9GTy2MnVAW0q0joXYQ1nb2NvKGyZo23EulcLG2TA9aDaHIcS3emAUv7Xg_C9pu6KKnLxK-6w-R-qKoQrxNZ87QmGDRhqy06GbaJc0ZNHbZak8QTF9glkWKZj3dBnQelrC5Ca0=w1311-h983-no" height="300px"/></p>

<p align="center"><img src="https://lh3.googleusercontent.com/llutsq0zUyEUmEy1QJXJm1fKO_J9iKkvyqwP9NHwoOfZCvC71J72QQKZQ7QWEy-KHhzD-HMfqqgbvBKdtLG_qgFRjgnvW8cd7fXGzi34SItJJZAjz4iBaDjUKw0m7hUllebR7aJA-44=w1311-h983-no" height="300px"/></p>

## Nosso time de João Pessoa - PB

<p align="center"><img src="https://lh3.googleusercontent.com/_q19ChKsb9-VUWfrcjBBbnRKocNROeRTWUcgx6wDZDcJ4-dyTGxAg6KS9cCPYRVliHiWaHOfJz-8SQ9GcfVseLzAIunnVYGxg_DoIELJoJkWm21Sv1xeaJFEc6XvuHD-XP5QADrLh1g=w1311-h983-no" height="300px"/></p>

**Comment by nielsonrolim** [comment]
Por favor, veja:
https://github.com/fractaltecnologia/jobs/issues/11
